/*
 *	Top level Cakefile.
 *
 *  This Cakefile serves the same purpose as the top level Makefile,
 *  ie, to run the "gen.sh" script with the given argument.
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/Cakefile,v 11.1.1.1 1998-01-29 06:15:07 mike Exp $
 */

%&:
	/bin/sh gen.sh %

all&::
	/bin/sh gen.sh
