/*
 *			libwdb/Cakefile
 *
 *  $Header: /usr/Backup/upgrade/brlcad/brlcad/libwdb/Cakefile,v 11.11.2.1 2003-12-03 17:55:59 erikg Exp $
 */
#define PRODUCTS	libwdb.ARCH_SUF
#define SRCDIR	libwdb
#define FILES	wdb reg ars arbn units pipe export nmg id \
		strsol cline bot skt extr mater nurb dynamic_geometry
#define	SRCSUFF	.c
#define MANSECTION	3

#define VERSION_VARIABLE	libwdb_version
#define LIBRARY_TITLE		"BRL-CAD Library for Writing Databases"

#include "../Cakefile.defs"

#if defined(RESOLVE_LIBRARIES)
#	define EXTRA_OBJ_NO_DEPENDENCY -lc -lm -brtl -L../.libbu.sp3 -lbu -L../.libbn.sp3 -lbn -L../.librt.sp3 -lrt
#endif

#include "../Cakefile.lib"
#include "../Cakefile.rules"
